### PR TITLE
Add Docker usage

### PR DESCRIPTION
**Pull request by RobLoach**
Decided to add [Docker](http://docker.io) support since I wasn't quire sure how to run it directly through lxc. Overall it works quite well.

Saw a few missing dependencies when building residualvm and supertux. Feel free to tweak further.

### CODE REVIEW

**Comment by strycore** [comment]
Thanks, I still have to try out Docker some day but this seems nice to have as it doesn't require firing up the container and sshing into it.

**Comment by strycore** [comment]
I just tried it and it works nicely :) 
I have one question though, how do I pass environment variables to build.sh, for example STAGING=1 ./build.sh for Wine.

**Comment by RobLoach** [comment]
Exposing environment variables through [ENV](https://docs.docker.com/engine/reference/builder/#env) will do it:

1. Add `ENV STAGING 0` to `Dockerfile` (default of STAGING becomes 0)
2. When running, execute `docker run ... --env STAGING=1 games/supertux`

**Comment by strycore** [comment]
thanks!
Now I have to figure out how to create a 32bit docker container and I can replace my lxc containers:)

**Comment by strycore** [comment]
https://github.com/docker/docker/issues/611
And it's not supported, guess it's back to using lxc since being able to run a 32bit container is a  requirement for pretty much everything we build.

**Pull request merged**
