### PR TITLE
Add PooN's WinePulse Latency Patch

### PR DESCRIPTION
**Pull request by 999gary**

### CODE REVIEW

**Comment by strycore** [comment]
Looks good

**Comment by strycore** [comment]
```
patching file dlls/winepulse.drv/mmdevdrv.c
Hunk #1 succeeded at 68 (offset -1 lines).
Hunk #2 succeeded at 384 with fuzz 2 (offset -22 lines).
Hunk #3 succeeded at 395 with fuzz 2 (offset -22 lines).
Hunk #4 FAILED at 1767.
1 out of 4 hunks FAILED -- saving rejects to file dlls/winepulse.drv/mmdevdrv.c.rej
```

**Comment by 999gary** [comment]
I tried patching myself and it seems that it doesn't work on 3.13, it works on 3.12 but I'm not sure if you want to build that version?

**Comment by strycore** [comment]
I can try with 3.12, shouldn't cause any problem

**Comment by strycore** [comment]
Seems like it was more an issue with staging, the build is currently running.

**Pull request merged**
