### PR TITLE
Add Retroarch Runner Build

### PR DESCRIPTION
**Pull request by RobLoach**
Add a [RetroArch](http://www.libretro.com/) build so that we can have a RetroArch runner. Some things to think about in regards to this:

- [ ] Any tweaks in `retroarch.cfg`?
- [ ] Any changes in cores to include?
- [ ] `retroarch.sh` should likely pass included arguments... `$1`?
- [ ] Also may or may not need the Lutris Runner
- [ ] Fix archive structure so that it's retroarch/* rather than buildbot/*
- [ ] Test more!

### CODE REVIEW

**Comment by strycore** [comment]
That's excellent! BTW, the goal in the next releases is not to have a retroarch runner but to migrate as many runners as we can to libretro cores. I am yet unsure if this will require shipping retroarch or if we can interact directly with the cores from our client.

**Comment by RobLoach** [comment]
> migrate as many runners as we can to libretro cores

That requires recompiling the project using the [libretro API](http://wiki.libretro.com/index.php?title=Libretro_API). Quite a large project, for any core, let alone "as many as we can". If it's something you believe possible, then that's awesome, let's do it. I have always believed libretro/RetroArch is the way to do everything. I have always been astounded by what it accomplishes, so if you think it's possible, let's do it... In the mean time, this is a good test in compiling Retroarch in a Linux-portable way.

We should have a lutris core for libretro, so that Lutris can launch Retroarch, with Lutris core, to launch Retroarch, to launch the Lutris core, to launch Retroarch.

**Comment by RobLoach** [comment]
Oh, you mean bring RetroArch cores over to Lutris runners?

**Comment by RobLoach** [comment]
As a side-note, this'll help us run [Cave Story](https://lutris.net/games/cave-story/) from the [download page](http://www.cavestory.org/download/cave-story.php), along with everything else that libretro handles.

**Comment by strycore** [comment]
No need for that, I just created an installer for the Freeware version of Cave Story :)

As for the libretro runners, I'll see how we handle that, we'll have to launch them somehow so, retroarch seems to be the best option currently (there are some python bindings but I'm not sure if they're usable and production ready).

**Pull request closed without merging**
