### PR TITLE
Remove patch for Reicast compilation issue (fixed upstream in https://github.com/reicast/reicast-emulator/pull/914)

### PR DESCRIPTION
**Pull request by dinoboy197**
This patch is no longer necessary since Reicast [fixed this issue upstream](https://github.com/reicast/reicast-emulator/pull/914) and new builds do not have this issue.

Question: how do we get a new build of the latest stable release of Reicast updated as a runner? The latest Reicast update was a few years back. I'm happy to help out here if that takes work off anyone's plate.

### CODE REVIEW

**Comment by RobLoach** [comment]
```
cd runners/reicast
./build.sh
```

If you build and verify it's good to go, I could upload the new version for you.

**Comment by dinoboy197** [comment]
Good call. Turns out I needed to adjust the build script a bit to:
* pull in the latest release tag, not just a random commit from master
* add extra libraries added for building
* update the directory with linux source

I've verified that the build works on a clean ubuntu bionic container with nothing but the dependencies from the readme at the root of this repo pre-installed.

**Comment by RobLoach** [comment]
Thanks so much! Trying the build now.

**Comment by dinoboy197** [comment]
@RobLoach I see the 64-bit build but not a 32-bit version.

image

Do we need to update anything else in Lutris so that when downloading the Reicast runner, it downloads the new version?

**Pull request merged**
